version: 2.1

orbs:
  node: circleci/node@5.0.3

ignore_forks: &ignore_forks
  branches:
    # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
    ignore: /pull\/[0-9]+/

only_forks: &only_forks
  branches:
    # Forked pull requests have CIRCLE_BRANCH set to pull/XXX
    only: /pull\/[0-9]+/

jobs:
  test:
    executor:
      name: node/default
      tag: '16.16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run the ESLint plugin tests

workflows:
  test_from_branches:
    jobs:
      - test:
          filters:
            <<: *ignore_forks
  test_from_forks:
    jobs:
      - test:
          filters:
            <<: *only_forks
