name: run-tests
run-name: Installs project and runs tests
on: [ push, pull_request ]
jobs:
  run-tests-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Run tests on Ubuntu with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
  run-tests-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ 20, 22 ]
    name: Run tests on Windows with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test