name: tests-on-branches
run-name: Installs project and runs tests, on repo branches
on: [ push, pull_request ]
jobs:
  run-tests-nix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    name: Run tests on Ubuntu with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test
  run-tests-win:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [ 14, 16 ]
    name: Run tests on Windows with Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn test